[ClassVersion("1.1.1.80"), FriendlyName("xVMComPort")]
class ITG_xVMComPort : OMI_BaseResource
{
    [Key] String Id;
    [Required] String VMName;
    [Required] UInt16 Number;
    [Write] String Path;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
